language: cpp
compiler:
- gcc
install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        # sudo add-apt-repository -y ppa:jonathonf/python-3.6
        #- sudo add-apt-repository -y ppa:beineri/opt-qt595-trusty
        - sudo apt-get update
        - sudo apt-get install gcc-5
        #- sudo apt-get install -y qt59-meta-full
script:
        # AWS
        - wget -qO - 'https://bintray.com/user/downloadSubjectPublicKey?username=arturfog' | sudo apt-key add -
        - echo "deb https://dl.bintray.com/arturfog/oss-arturfog xenial main" | sudo tee -a /etc/apt/sources.list 
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated amazon-s3-cpp-sdk
        - sudo apt-get install -y --allow-unauthenticated qt-everywhere

        # qtS3Browser
        - git clone --depth 1 https://github.com/arturfog/qtS3Browser.git
        - mkdir build
        - cd build
        - export QTDIR=/opt/Qt5.10
        - QMAKE_CXX=g++-5 QMAKE_CC=gcc-5 /opt/Qt5.10/bin/qmake -o Makefile ../qtS3Browser/s3Browser.pro -spec linux-g++ CONFIG+=release
        - make
notifications:
        email: false
