language: cpp

install:
        - sudo apt-get update -qq
        - sudo apt-get install -y python3-pip
script:
        sudo pip3 -U install conan
        conan remote add arturfog-conan-repo https://api.bintray.com/conan/arturfog/oss-conan
notifications:
        email: false
