language: cpp
os: linux
dist: bionic
compiler:
  - gcc
jobs:
  include:
    - os: osx
      osx_image: xcode11
    - os: linux
      services: docker
      dist: bionic
      env: TRAVIS_BUILD_TYPE="Release"

addons:
  sonarcloud:
    organization: "arturfog-github"
    token:
      secure: "EkbBnnRu7aGDS7Nn8+YjicaBh3YNwARSgvAx78e9C+tPpdJWnZ/tbOT/Hphm+Pv2HHOkE/f1SvWHRoe7SJlwIIrN4JSKnpqdUOa2id6U1ipnYEd0Sc9Nzt/p0DgpXWQ6vCfemATUN9WZYLnKhHO8gRfGib/Zbs4fcVuBMHN+ACAB4fmhkO/I46XVMY1/dgrUJVbTdrEwC3qvAXrcwM+kupmqJbTZiO90FTenVBqKlK7HtcJTbVS2zwEre/OxaTv338Fm63eQvdDpr/cPO816JiK7uOijVUyW+w5qyGdfhnBUxKLNJ86D2/+GqVHYfsXYT/3j8S0H6CJFVtvpi1ic2nOxsT/jfrsWrNTZniRh0LsmpCx9tQkxzLFB8fvUx4T0vg79tpjpqiFnI34+Oi9KWf5EH471ovlJ/rbQ631/dfueW0gzQgJkGPglCm2+m4rTtcMVQMZO6nnZtw0Hr7rX3SfGvCrTvrdq0iDUIFaHtabFJodfeIPUL7o4vxfJAA8Ou9yXeuAsqsQ9R0LH8v55Wr0ANf1Ofl6yz8PubLfbPxCOihbiWjvEhoA+dHtsNMhAcMiflDr4PU7kLIRNNWjiHqOmEetSZ4253LNNo/vu990XNU2MhJqOZvkAS4fZKKwt2KQw31yBa84TfCjrYF4EN5ovwBWAhvMqV8klBm1ubv8="

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker pull ubuntu:bionic; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker run -it -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -v $HOME/.ccache:$HOME/.ccache -v $HOME/.sonar:$HOME/.sonar -w $TRAVIS_BUILD_DIR --env CC --env CXX --env TRAVIS_BUILD_DIR --env TRAVIS_BUILD_TYPE ubuntu:bionic /bin/bash ./ci_build.sh; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then ./ci_macos.sh; fi

deploy:
  - provider: bintray
    skip_cleanup: true
    file: ".travis_desc.json"
    user: "arturfog"
    key:
      - secure: "RQ0uErGhXAMwNImMHk4ZIOwiazOXGiFGlEEfPHtZpH9p5FzcRFYdL9ClcwRscbArW1xzLbTYOMs4fkiExZp9h4fZ/Qc8lwM+Z2YYmNwKSgh5MVKgPfsGaeI8bcW4l4ZBxNZ4ZrUAfJeQZDVsZNAxc/Fy3B7h69Px2WDaWdXq/RDFK0CmkfKWfmI6pIxbmwsE14ehniA/fwXpaD+sOpXby2PbGDmv+wvsZASYYttBiz4/RZAU/2oDB+oAF3NApLzC8p4xC7pJ/MRJ9XHcHVDjaD1gmGZKbfWKIWSJPicXlw2YS5/3QyqF573Y9iCTLq37kL4HMmgqxtj0pk1nEnz8osDWZaIf4VjL0Oi7gW2kwSs8TWtJ2shbKC0tezdAqTnBaMSP0NpV6Slp2fOGl+2TIF1zSTdQaA2FHtQgZ7fHC4PkVoctc7x3r6wos/vWhueWSXLhR0576hm0uYLkiBxNU/JtTs5uqJaEacbKfy9RwxOzmjRbw6oducwhhG0aWvd386u5xlxkZqTEd9szKX4XNuuoTUHfCrDmZ1Q2q3gfnBNPJeKLnZUKQ6PCyhn4TyH7FEJ0WLV9PMtVUIfGt5jycH5egQ+e7dmdzzAOtoOkVioZ/EelxN7nE2CdHXKF7ackVqvWpQYQYAMuPZZR/09fWNr/TFHkniG+pxm7fo8w3Yo="
    on: 
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: bintray
    skip_cleanup: true
    file: ".travis_desc_mac.json"
    user: "arturfog"
    key:
      - secure: "RQ0uErGhXAMwNImMHk4ZIOwiazOXGiFGlEEfPHtZpH9p5FzcRFYdL9ClcwRscbArW1xzLbTYOMs4fkiExZp9h4fZ/Qc8lwM+Z2YYmNwKSgh5MVKgPfsGaeI8bcW4l4ZBxNZ4ZrUAfJeQZDVsZNAxc/Fy3B7h69Px2WDaWdXq/RDFK0CmkfKWfmI6pIxbmwsE14ehniA/fwXpaD+sOpXby2PbGDmv+wvsZASYYttBiz4/RZAU/2oDB+oAF3NApLzC8p4xC7pJ/MRJ9XHcHVDjaD1gmGZKbfWKIWSJPicXlw2YS5/3QyqF573Y9iCTLq37kL4HMmgqxtj0pk1nEnz8osDWZaIf4VjL0Oi7gW2kwSs8TWtJ2shbKC0tezdAqTnBaMSP0NpV6Slp2fOGl+2TIF1zSTdQaA2FHtQgZ7fHC4PkVoctc7x3r6wos/vWhueWSXLhR0576hm0uYLkiBxNU/JtTs5uqJaEacbKfy9RwxOzmjRbw6oducwhhG0aWvd386u5xlxkZqTEd9szKX4XNuuoTUHfCrDmZ1Q2q3gfnBNPJeKLnZUKQ6PCyhn4TyH7FEJ0WLV9PMtVUIfGt5jycH5egQ+e7dmdzzAOtoOkVioZ/EelxN7nE2CdHXKF7ackVqvWpQYQYAMuPZZR/09fWNr/TFHkniG+pxm7fo8w3Yo="
    on: 
      branch: master
      condition: $TRAVIS_OS_NAME = osx

notifications:
  email: false
