language: cpp
services: docker

os: linux

compiler:
  - gcc

env:
  matrix:
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="xenial"

before_script:
  - docker pull ubuntu:$UBUNTU

script:
  - >-
    docker run -it \
      -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
      -v $HOME/.ccache:$HOME/.ccache \
      -w $TRAVIS_BUILD_DIR \
      --env CC \
      --env CXX \
      --env TRAVIS_BUILD_DIR \
      --env TRAVIS_BUILD_TYPE \
      ubuntu:$UBUNTU \
      sh ./ci_build.sh

notifications:
        email: false
