language: cpp
compiler:
- gcc
install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        # sudo add-apt-repository -y ppa:jonathonf/python-3.6
        - sudo add-apt-repository ppa:beineri/opt-qt595-trusty
        - sudo apt-get update -qq
        # sudo apt-get install -y gcc-7
        - sudo apt-get install -y qt59-meta-full
        # dev packaes for AWS SDK
        - sudo apt-get install -y zlib1g-dev libssl-dev libcurl4-openssl-dev
script:
        # AWS
        - git clone --depth 1 https://github.com/aws/aws-sdk-cpp.git
        - cd aws-sdk-cpp
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DENABLE_TESTING=OFF -DBUILD_ONLY=s3 -DBUILD_ONLY=transfer
        - make -j 2
        - sudo make DESTDIR=$HOME/.local install
        - cd ../../
        # qtS3Browser
        - git clone --depth 1 https://github.com/arturfog/qtS3Browser.git
        - mkdir build
        - cd build
        - qmake -o Makefile ../qtS3Browser/s3Browser.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
notifications:
        email: false
