# clone directory
clone_folder: c:\projects\qts3browser

os: Windows Server 2012 R2

platform:
 - x86

configuration: Release

install:
  - set MINGW_PATH=C:\Qt\Tools\mingw530_32
  - set QTDIR=C:\Qt\5.11.1\mingw53_32
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%MINGW_PATH%\bin;C:\msys\bin\;%QTDIR%\bin;%PATH%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  # Install Inno Setup
  - choco install InnoSetup

build_script:
  - mkdir c:\projects\aws
  - cd .\deb_aws
  
  - git clone --depth 1 https://github.com/aws/aws-sdk-cpp.git
  
  - cd aws-sdk-cpp
  - mkdir build && cd build
  - cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON -DENABLE_TESTING=OFF -DBUILD_ONLY=s3 -DBUILD_ONLY=transfer ..
  - mingw32-make -j8

  - cd ..\..\

  - cd ..\
  - mkdir .\build
  - cd .\build

  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-core\Debug\aws-cpp-sdk-core.dll c:\projects\aws
  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-s3\Debug\aws-cpp-sdk-s3.dll c:\projects\aws
  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-transfer\Debug\aws-cpp-sdk-transfer.dll c:\projects\aws
  
  - xcopy /F /E C:\projects\qts3browser\deb_aws\aws-sdk-cpp\aws-cpp-sdk-core\include\* c:\projects\aws
  - xcopy /F /E C:\projects\qts3browser\deb_aws\aws-sdk-cpp\aws-cpp-sdk-s3\include\* c:\projects\aws
  - xcopy /F /E C:\projects\qts3browser\deb_aws\aws-sdk-cpp\aws-cpp-sdk-transfer\include\* c:\projects\aws

  - qmake -v && qmake ..\s3Browser.pro CONFIG+=release && mingw32-make -j 2

  # Bundle all dependencies
  - ps: |
      windeployqt --qmldir qml release\s3browser.exe --dir distrib
      cp c:\projects\aws\aws-cpp-sdk-*.dll distrib
      7z a -y distrib.zip distrib

  # Build the installer
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - ISCC /Q qts3browser.iss

after_build:
- ps: |
    appveyor PushArtifact distrib.zip
    appveyor PushArtifact C:\qts3browser_win_setup.exe

# to disable deployment
#deploy: off
