# clone directory
clone_folder: c:\projects\qts3browser

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

configuration: Release

build_script:
  - cd .\deb_aws
  - build.bat
  - cd ..\
  - mkdir .\build
  - cd .\build
  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-core\Debug\aws-cpp-sdk-core.dll .
  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-s3\Debug\aws-cpp-sdk-s3.dll .
  - cp C:\projects\qts3browser\deb_aws\aws-sdk-cpp\build\aws-cpp-sdk-transfer\Debug\aws-cpp-sdk-transfer.dll .
  - qmake -v && qmake ..\s3Browser.pro CONFIG+=release && mingw64-make

# to disable deployment
#deploy: off
