name: qts3browser
version: '1.0' 
summary: Amazon S3 client written in QT
description: |
          Amazon S3 client written in QT.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  s3browser:
    command: desktop-launch $SNAP/opt/s3browser/bin/s3browser
    plugs: [home, network, x11]

parts:
  aws:
    source: https://github.com/aws/aws-sdk-cpp.git
    source-depth: 1
    build-packages:
            - zlib1g-dev
            - libssl-dev
            - libcurl4-openssl-dev
    stage-packages:
            - libssl1.1
    plugin: cmake
    stage: 
            - include/*
            - usr/*
            - lib/*
            - -lib/pkgconfig
    configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DBUILD_SHARED_LIBS=ON
            - -DENABLE_TESTING=OFF
            - -DBUILD_ONLY=s3;transfer
  desktop-qt5:
    stage:
            - bin/*
            - etc/*
            - usr/*
            - lib/*
            - var/*
            - -usr/share/pkgconfig
  application:
    source: https://github.com/arturfog/qtS3Browser.git
    build-packages:
            - qtdeclarative5-dev
    stage-packages:
            - libc6
    plugin: qmake
    qt-version: qt5
    after: [aws, desktop-qt5]
